-- Formula 8
iright("seq0", "imply4")
focus("seq1", "imply3")
ileft("seq2", "imply5")
iright("seq3", "imply2")
focus("seq5", "imply1")
ileft("seq6", "imply7")
iright("seq7", "imply0")
ileft("seq9", "imply7")
iright("seq10", "imply0")
restart("seq12", "A")
focus("seq13", "imply8")
ileft("seq14", "imply12")
iright("seq15", "imply2")
restart("seq17", "C")
focus("seq18", "imply3")
ileft("seq19", "imply15")
iright("seq20", "imply2")

-- -- Formula 3
-- iright("seq0", "imply5")
-- iright("seq1", "imply4")
-- focus("seq2", "imply1")
-- ileft("seq3", "imply6")
-- iright("seq4", "imply0")
-- focus("seq6", "imply3")
-- ileft("seq7", "imply9")
-- iright("seq8", "imply2")
-- ileft("seq10", "imply6")
-- iright("seq11", "imply0")
-- ileft("seq13", "imply9")
-- iright("seq14", "imply2")
-- ileft("seq16", "imply9")
-- iright("seq17", "imply2")
-- restart("seq19", "r")
-- focus("seq20", "imply8")
-- ileft("seq21", "imply18")
-- iright("seq22", "imply2")
-- restart("seq24", "q")
-- focus("seq25", "imply10")
-- ileft("seq26", "imply21")
-- iright("seq27", "imply0")
